name: Build on ubuntu

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build with Gradle
        run: ./gradlew build

      - name: Collect files for distribution
        run: ci/collect-artifacts.sh gtk-meteo

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: gtk-meteo
          path: gtk-meteo
          if-no-files-found: error
