name: Build on debian

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/bailuk/java-gtk/gtk4-debian:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build with Gradle
        run: ./gradlew build

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: mapsforge-gtk
          path: build/libs/*
          if-no-files-found: error
