name: Build on Ubuntu

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: ./gradlew build
      - run: ci/collect-artifacts.sh gtk-meteo/gtk-meteo
      - uses: actions/upload-artifact@v3
        with:
          name: gtk-meteo
          path: gtk-meteo
          if-no-files-found: error
